CREATE TABLE [dbo].[Favorite] (
    [UserID] INT NOT NULL,
    [PID]    INT NOT NULL,
    PRIMARY KEY CLUSTERED ([UserID] ASC, [PID] ASC),
    FOREIGN KEY ([PID]) REFERENCES [dbo].[Product] ([PID]) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY ([UserID]) REFERENCES [dbo].[Customer] ([UserID]) ON DELETE CASCADE ON UPDATE CASCADE
);

