CREATE TABLE [dbo].[OrderItem] (
    [Quantity] INT NOT NULL,
    [PID]      INT NOT NULL,
    [OID]      INT NOT NULL,
    PRIMARY KEY CLUSTERED ([PID] ASC, [OID] ASC),
    FOREIGN KEY ([OID]) REFERENCES [dbo].[Orders] ([OID]) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY ([PID]) REFERENCES [dbo].[Product] ([PID]) ON DELETE CASCADE ON UPDATE CASCADE
);

