### SIGNUP
POST http://localhost:3000/api/v1/auth/signup
Content-Type: application/json

{
  "name": "Hazem Hamdy",
  "email": "test1@gmail.com",
  "password": "test@1234"
}

### SIGNIN
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "test1@gmail.com",
  "password": "tesst@1234"
}


### GET ALL USERS
GET http://localhost:3000/api/v1/users

